### ISSUE TITLE
ホーム画面の遊び方を押すと遊び方説明が始まる

### ISSUE THREAD

**Issue by saitohiraku** [saitohiraku/intern-quiz-hiraku#15]
## 概要 (Summary):
説明が見れる(mockで完成済)
## 誰が使うか (For whom):
ユーザ
## 何のために or どのように実装するか (For what):
初めて遊ぶユーザが遊び方をみるため
## 達成目標:
遊び方が見れる

**Comment by hikaru-nakamura-thedott** [comment]
#10 で実装済み
