### ISSUE TITLE
図鑑情報の登録

### ISSUE THREAD

**Issue by saitohiraku** [saitohiraku/intern-quiz-hiraku#48]
## 画面・API (Page or API):
(URL, 画面の名前, API名など具体的に: URL, Page name or API please fill it concretely)
## 再現する手順 (Steps to reproduce the problem):
 1. 
 2. 
 3. 
 4. 
## その他の情報 (Other informations): 
(エラーログやスクリーンショット、データベースの情報、その他開発に有効と思われる情報: Error log, screenshot, database or other informations)
## 詳細情報 (Detailed informations):
図鑑に登録する件数-15
一種類に魚に対して何件のtrueとなる質問を入れるか-最低3-

![Image](https://github.com/user-attachments/assets/309c1dfe-8c18-4ebd-8deb-67dd68206344)
![Image](https://github.com/user-attachments/assets/f4489976-def6-4df5-b507-256e58326139)
![Image](https://github.com/user-attachments/assets/c33a6056-08c8-4ecb-b298-d5064adff907)

**Comment by hikaru-nakamura-thedott** [comment]
登録が完了できたのでクローズ
