### ISSUE TITLE
図鑑テーブル　'マスター'

### ISSUE THREAD

**Issue by saitohiraku** [saitohiraku/intern-quiz-hiraku#7]
## 概要 (Summary):
　魚の名前、画像
## 誰が使うか (For whom):
開発者
## 何のために or どのように実装するか (For what):
魚の情報を入れるため
## 達成目標:
定義書作成

**Comment by saitohiraku** [comment]
https://docs.google.com/spreadsheets/d/1hj-w7YARyXfOGC1a5vx5c6nwnkk0pcPX2_cKkaYv6BA/edit#gid=0

**Comment by hikaru-nakamura-thedott** [comment]
確認しました。
